### ISSUE TITLE
Blog template: 404-page not found

### ISSUE THREAD

**Issue by HelmerDenDekker** [TeamXerbutri/teamxerbutri.github.io#10]
## Bug description
https://teamxerbutri.github.io/avontuur/vbmh

Github error:

If this is your site, make sure that the filename case matches the URL as well as any file permissions.
For root URLs (like http://example.com/) you must provide an index.html file.

**Comment by HelmerDenDekker** [comment]
https://dev.to/mktcode/github-pages-with-dynamic-routes-dli

**Comment by TeamXerbutri** [comment]
Tested and resolved
