### ISSUE TITLE
Use GeoJson from CMS instead of KMLs

### ISSUE THREAD

**Issue by HelmerDenDekker** [TeamXerbutri/teamxerbutri.github.io#106]
Use geojson with properly defined properties instead of the KML

Use:
- category
- routeId

Solves the bug of not showing the images and having the right urls.

**Comment by HelmerDenDekker** [comment]
This was quite heavy. But nailed it. PR's will be coming along.

**Comment by TeamXerbutri** [comment]
Ready for test

**Comment by HelmerDenDekker** [comment]
tested and works
