### ISSUE TITLE
Minor Bugs

### ISSUE THREAD

**Issue by HelmerDenDekker** [TeamXerbutri/teamxerbutri.github.io#119]
**Zoomslider**

The +- zoomslider looks bad on mobile, it should have far smaller +-

**Overlay-dismiss does not work on mobile**

On the computer it works, but on mobile it does not close the overlay if you click somewhere else

**Safari urlbar problem**

On safari mobile, the urlbar blocks the lower portion, you can "hide" the urlbar, but I cannot in maps, since it is fixed.

**Map Links**

On the computer the links turn black (background)
On mobile, they flash black when you click them

**Comment by HelmerDenDekker** [comment]
see tx119--0verlay-dismiss-fix

**Comment by TeamXerbutri** [comment]
All fixed except the overlay-dismiss
