### ISSUE TITLE
Bug - All - Prod: Android-chrome favicon not found

### ISSUE THREAD

**Issue by TeamXerbutri** [TeamXerbutri/teamxerbutri.github.io#13]
GET https://teamxerbutri.github.io/android-chrome-192x192.png 404 (Not Found)

**Comment by TeamXerbutri** [comment]
The file is in the repo, but cannot be found => 404. What if we put it in the public folder?

**Comment by HelmerDenDekker** [comment]
Put it in public 
DO NOT FORGET If this works - remove this in the root folder.

If this does not work, put it in data

**Comment by TeamXerbutri** [comment]
Is deleted, works in public folder.
