### ISSUE TITLE
Index: If you click anywhere, the menu disappears

### ISSUE THREAD

**Issue by HelmerDenDekker** [TeamXerbutri/teamxerbutri.github.io#29]
Probably this has to do with js working for mobile apps or the blog page

**Comment by HelmerDenDekker** [comment]
Menu disappearing sorted.
Now, the mobile does not work anymore AND on window resize it looks weird

**Comment by TeamXerbutri** [comment]
Thanks for the fix

**Comment by TeamXerbutri** [comment]
Ready for test

**Comment by HelmerDenDekker** [comment]
On production
