### ISSUE TITLE
Automatic routing system

### ISSUE THREAD

**Issue by TeamXerbutri** [TeamXerbutri/teamxerbutri.github.io#3]
Investigate first.

It should do routing just like xerbutri.nl.
So buildings go to /avontuur/FolderAbbreviation

**Comment by TeamXerbutri** [comment]
Quick insight, I think it only uses the "route" to fill the template in PHP, could be done like that in JS as well.

**Comment by HelmerDenDekker** [comment]
PHP is MVC, so there is a controller filling the template from DB input.

### Why not make frontend MVC? And fill it from Json input?

[Is MVC dead for frontend?](https://www.freecodecamp.org/news/is-mvc-dead-for-the-frontend-35b4d1fe39ec/)

[Classic MVC in JS](https://medium.com/@patrickackerman/classic-front-end-mvc-with-vanilla-javascript-7eee550bc702)

Controllers and models are quite rigid. 
Nowadays frontends, and certainly JS-frameworks moved away from MVC, becoming more event-based, and having web components. 
In MVC the model and controller dictate what happens on your page. But MAYBE, for this viewer, and its interests, you want the page to look completely different.... Think about it.. Maybe I could write a blog??

**Unidirectional architecture, is this the future?** 
https://staltz.com/unidirectional-user-interface-architectures.html

### Anywayzzz, concluding thoughts
- Going directly to MVC might be fastest.
- Creating our ow routing platform and Smart Frontend is definitely slowest
- Using Vue to do the routing might be a good idea - as basis- (?)

**Comment by HelmerDenDekker** [comment]
Reading this back:
The current website is heavy MVC.
There are models (as expressed in PHP), views (sorta-HTML pages FFF) and controllers (in PHP) filling these views.

So.
Routes.
- /
- /map
- /avontuur/{abbrev}
- /vier/{cat}.php?lang={langid}
- /vier/{cat}/{type}.php?geef={subid}


I have the pages and js to fill or create index, map, avontuur
All I need is some kind of system allowing me to reroute all the /avontuur/*  /vier/* and /*.php to some place better.

**Comment by TeamXerbutri** [comment]
Solved with the current prototype, it seems to work just fine. Thanks!!
