### ISSUE TITLE
Index: On changing index, the site should retrieve the new bloginfo and load it.

### ISSUE THREAD

**Issue by TeamXerbutri** [TeamXerbutri/teamxerbutri.github.io#67]
Now it just translates everything, while not everything is available in english

**Comment by HelmerDenDekker** [comment]
PR on fire!!

**Comment by TeamXerbutri** [comment]
Merged to develop

**Comment by TeamXerbutri** [comment]
Ready for test

**Comment by TeamXerbutri** [comment]
It does not completely react as it should. Minor issue will be ackled later
