### ISSUE TITLE
photoswipe picture gallery

### ISSUE THREAD

**Issue by HelmerDenDekker** [TeamXerbutri/teamxerbutri.github.io#80]

**Comment by HelmerDenDekker** [comment]
PR

**Comment by TeamXerbutri** [comment]
First version merged to dev.
Design - as - was
Also: If there were no titles, there will be no titles now.

**Comment by HelmerDenDekker** [comment]
Ja, scope creep. Hou ik in de gaten.

**Comment by TeamXerbutri** [comment]
Okay.
First version is ready for test.

**Comment by TeamXerbutri** [comment]
Is available.
- Improve the design
- Current site has no titles
- Add captions for Spoor

**Comment by HelmerDenDekker** [comment]
PR for design fix

**Comment by HelmerDenDekker** [comment]
I need dynamic import in js for the captions to work.

**Comment by HelmerDenDekker** [comment]
PR!

**Comment by TeamXerbutri** [comment]
Merged to develop, going live!

**Comment by TeamXerbutri** [comment]
Test

**Comment by HelmerDenDekker** [comment]
Two PRs with small fixes, then lets close this issue, mkay?
