### ISSUE TITLE
English and french translations of about page and UE page

### ISSUE THREAD

**Issue by TeamXerbutri** [TeamXerbutri/teamxerbutri.github.io#84]
The about page was a simple photo collage
https://xerbutri.nl/vier/xerbutri/teamx.php?lang=2

UE
https://xerbutri.nl/vier/xerbutri/UE.php?lang=2
https://xerbutri.nl/vier/xerbutri/UE.php?lang=4

How to survive
https://xerbutri.nl/vier/xerbutri/SE.php?lang=2

Even in german!!
https://xerbutri.nl/vier/xerbutri/SE.php?lang=3
https://xerbutri.nl/vier/xerbutri/SE.php?lang=4

However, it was quite minimal

**Comment by HelmerDenDekker** [comment]
In TX72 / CMS now

**Comment by TeamXerbutri** [comment]
Merged to dev

**Comment by TeamXerbutri** [comment]
Tested
