### ISSUE TITLE
The current website contains some not-published blogs from 5-6 migration

### ISSUE THREAD

**Issue by TeamXerbutri** [TeamXerbutri/teamxerbutri.github.io#90]
See if you can easily fix it.

**Comment by HelmerDenDekker** [comment]
In the new CMS I created an IsPublished. So when I have the new export mechanism, this will be solved.

**Comment by HelmerDenDekker** [comment]
Tx72 will solve this issue

**Comment by TeamXerbutri** [comment]
Merged to dev.
Test

**Comment by TeamXerbutri** [comment]
Tested
