### ISSUE TITLE
If rating is zero, do not show rating

### ISSUE THREAD

**Issue by HelmerDenDekker** [TeamXerbutri/teamxerbutri.github.io#93]
Xerbutri 4 blogs do not seem to have rating, while there is a rating on the (four) website. 
Maybe something went wrong in the migration?

**Comment by HelmerDenDekker** [comment]
Should be solved when new export / cms is ready

**Comment by TeamXerbutri** [comment]
Merged to dev

**Comment by TeamXerbutri** [comment]
Tested
